# decentralized_control/config/factorial_design.yaml
parameters:
  num_tasks: [4, 8, 16, 32]
  comm_delay: [0, 50, 200, 500]  # ms
  packet_loss: [0, 0.1, 0.3, 0.5]
  epsilon: [0.01, 0.05, 0.2, 0.5]

experiment:
  num_runs: 10  # Number of repetitions per configuration
  simulation_time: 300  # seconds
  robot_count: 2
  workspace_size: [10, 8]
  random_seed: 42
  failure_probability: 0.5  # Probability of injecting a failure
  
analysis:
  confidence_level: 0.95
  anova_significance: 0.05
  include_interactions: trues