# config/price_stability_test.yaml
parameters:
  num_tasks: [16]
  comm_delay: [0]
  packet_loss: [0.0]
  epsilon: [0.01, 0.05, 0.2, 0.5, 1.0, 5.0]
  termination_mode: "price-stabilized"
  price_stability_threshold: [0.001, 0.01, 0.05, 0.1]  # Test different thresholds

experiment:
  num_runs: 3
  simulation_time: 300
  robot_count: 2
  workspace_size: [10, 8]
  random_seed: 42
  failure_probability: 0.0
  
visualization:
  enabled: true
  save_plots: true
  plot_dir: "price_stability_plots"