function utils = utils_manager()
    % UTILS_MANAGER Centralized access to all utility functions
    % This provides a single entry point for all utilities to avoid naming conflicts
    
    utils = struct(...
        'env', environment_utils(), ...
        'robot', robot_utils(), ...
        'task', task_utils(), ...
        'auction', auction_utils(), ...
        'kinematics', kinematics_utils(), ...
        'motion_planning', motion_planning_utils(), ...
        'sim', simulation_supervisor() ...
    );
end